# Generated by Django 5.1.6 on 2025-02-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_options_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='strip_payment_intent',
            new_name='stripe_payment_intent',
        ),
    ]
