# Generated by Django 5.1.5 on 2025-01-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='linkmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
