# Generated by Django 5.1.5 on 2025-01-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.TextField(),
        ),
    ]
