# Generated by Django 5.1.5 on 2025-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='degree',
            field=models.CharField(default='', max_length=200),
        ),
    ]
