# Generated by Django 5.1.5 on 2025-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
